project:
  type: website
  output-dir: docs
  preview: 
    port: 4005
    browser: true

website:
  favicon: favicon.png
  title: "Koushik's Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: resume.qmd
        text: Resume

    right:
      - href: about.qmd
      - icon: github
        href: https://www.github.com/koushikkhan/
      - icon: twitter
        href: https://www.twitter.com/koushikKhan92/
      - icon: linkedin
        href: https://linkedin.com/in/koushikkhan/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

