---
title: "About"
subtitle: "Educational, Professional and Personal Background"
from: markdown+emoji
resources:
  - .nojekyll
---

## {{< fa graduation-cap >}} Education
+ M.Sc. in Statistics (2015) - Visva Bharati University, India
+ B.Sc. in Statistics (2013) - Visva Bharati University, India

## {{< fa user-tie >}} Professional Career History
+ Lead Data Scientist at Tiger Analytics India Consulting Pvt. Ltd. (Oct, 2024 - Present)
+ Principal Data Scientist at S&P Global, Market Intelligence (Sep, 2023 - Sep, 2024)
+ Senior Data Scientist at S&P Global, Commodity Insights (Aug, 2021 - Sep, 2023)
+ Data Scientist at IBM India Pvt. Ltd. (Oct, 2016 - Jul, 2021)
+ Data Analyst at BCausE Enterprise Pvt. Ltd. (Oct, 2015 - Aug, 2016)

## {{< fa laptop >}} Current Job Responsibilities
+ Leading the development & maintenance for [TigerML](https://www.tigeranalytics.com/open-ip/foundation/tigerml/), an in-house product developed for addressing challenges in data science projects
+ Leading various cross functional analytics initiatives
+ Developing solutions for various customer facing engagements

## {{< fa umbrella-beach >}} Things I Love Apart From Work
+ Cooking
+ Teaching
+ Reading books
+ Listening to audio stories, especially the Bengali Classics
+ Travelling to historical places