---
title: "Skills and Expertises"
from: markdown+emoji
---

Along the journey in my career, I have worked on various projects, all of them may not be worth of mentioning. I have handpicked few of them here along with the tools and methodologies used.

## {{< fa building-columns >}} Academics
+ Digitization of class notes, preparation of project reports
    + {{< fa screwdriver-wrench >}} Tools
        + $\LaTeX$ as the rendering engine
        + R with Sweave and knitr packages

+ Performing computations for 'Design of Experiments' problems
    + {{< fa screwdriver-wrench >}} Tools
        + C programming 

## {{< fa briefcase >}} BCausE Enterprise Pvt. Limited (2015-2016)
+ Predicting the names of human body parts from a corpus of digitized prescriptions using text classification
    + {{< fa screwdriver-wrench >}} Tools
        + Heavily relied on regex for data cleansing
        + NLP libraries based on Python
        + MongoDB at the back-end
        + Flask for REST API as front-end

## {{< fa briefcase >}} IBM India Pvt. Ltd. (2016-2021)
+ Analysing customer complaints (a.k.a tickets) from various sources and predicting root causes using clustering and text classification respectively
    + {{< fa screwdriver-wrench >}} Tools
        + Python (as machine learning base)
        + SQL at the back-end
        + Little bit of ShellScript to integrate the model with other modules
        + Flask for REST API as front-end
        + docker for packaging the ml application
        + Kubernetes used for deployment of the docker image

+ Serving search queries to customers by designing a small scale search engine built on customer Feedbacks and FAQs using information retrieval algorithm
    + {{< fa screwdriver-wrench >}} Tools
        + Singular value decomposition to understand word-to-word relationship 
        + Pandas as data processing toolkit
        + Numpy for matrix facorization implementation

+ Understanding the effects of various factors like advertisement, promotion, weather on sales of several commodities, analysing ROI year-on-year basis and forecasting the furure sales using Marketing Mix Modeling
    + {{< fa screwdriver-wrench >}} Tools
        + R with dplyr as the data processing toolkit
        + Base R for model development
        + SQL at the back-end

## {{< fa briefcase >}} IHS Markit and S&P Global Inc. (2021-Present)
+ Analysing shipping data on a daily basis
    + {{< fa screwdriver-wrench >}} Tools
        + PySpark as the data processing engine 
        + Excel for adhoc analysis and reporting
        + AWS as the cloud platform
        
+ Cargo grade identification using text classification
    + {{< fa screwdriver-wrench >}} Tools
        + Python (as machine learning base)
        + S3 for Local Deployment
        + ShellScript for automation

+ Building data pipeline incorporate external data from various sources
    + {{< fa screwdriver-wrench >}} Tools
        + R for developing data pipelines
        + ShellScript for integration as automation
        + AWS as cloud platform

